### ISSUE TITLE
在iframe嵌套页面中，日期控件显示位置有问题，

### ISSUE THREAD

**Issue by zhihuihu** [amazeui/datetimepicker#17]
在iframe嵌套页面中，日期控件显示位置有问题，
![image](https://user-images.githubusercontent.com/16135245/29595731-f74b7c70-87eb-11e7-880c-d7e9a782dd34.png)

**Comment by zhihuihu** [comment]
请速速更新啊，

**Comment by dumyjob** [comment]
+1, 能否实现my97-wdatepikcer一样跨iframe显示日期控件

**Comment by zhihuihu** [comment]
已经没有人维护了，我要关闭这个问题了
