### ISSUE TITLE
This page bug ,in qq browser.

### ISSUE THREAD

**Issue by bihubihu** [amazeui/datetimepicker#3]
http://amazeui.github.io/datetimepicker/docs/demo.html#href%3Dhttps%3A%2F%2Fgithub.com%2Famazeui%2Fdatetimepicker%26text%3DStar%26data.count.api%3D%26data.count.href%3Dhttps%3A%2F%2Fgithub.com%2Famazeui%2Fdatetimepicker%26data.count.aria.label%3D%26data.style%3D%26data.icon%3D%26aria.label%3D

the footer is in the middle of page.
and how to upload the screenshot?
Thanks

**Comment by Minwe** [comment]
https://help.github.com/articles/issue-attachments/
