### ISSUE TITLE
onRender配置项不起作用

### ISSUE THREAD

**Issue by roc6** [amazeui/datetimepicker#5]
我在代码中也没有搜索到任何与render有关的内容，onRender貌似没有起作用

**Comment by minwe** [comment]
看了一下代码，确实没有这个选项。
但官方文档上却写了。

你试试使用 `startDate` 和 `endDate` 这两个选项。

**Comment by minwe** [comment]
http://amazeui.github.io/datetimepicker/docs/demo.html#%E5%B8%A6%E5%88%A0%E9%99%A4%E7%9A%84%E7%BB%84%E4%BB%B6%E5%BA%94%E7%94%A8 这个例子

**Comment by minwe** [comment]
如果需要根据用户输入动态调整，可以用下面的方法：

```js
$('#datetimepicker').datetimepicker('setStartDate', '2012-01-01');

$('#datetimepicker').datetimepicker('setEndDate', '2016-01-01');
```

**Comment by roc6** [comment]
谢谢解答。startDate和endDate作用有局限，比如设定12月12日 9:00 - 18:00 至 12月14日 9:00 - 18:00的时间可选。
