### ISSUE TITLE
禁止选择小于今天的日期，但是在点击prev的情况下，会出现过去日期

### ISSUE THREAD

**Issue by beijiyibei** [amazeui/datetimepicker#7]
禁止选择小于今天的日期后，点击prev时，当面板是month或year情况下下能选择过去日期。
如何在任何情况下都不可以选择过去的年，月，日

**Comment by minwe** [comment]
1d24b52cf374b1aed37a01568afdc1b47eeacd34 中已经修复此问题，请重新下载。

**Comment by beijiyibei** [comment]
十分感谢！
