### ISSUE TITLE
需要引入哪些文件

### ISSUE THREAD

**Issue by zhuCheer** [amazeui/datetimepicker#8]
下载后，需要引入几个js，

<script src=/datetimepicker/js/amazeui.datetimepicker.min.js'></script>
<script type="text/javascript" src=" /datetimepicker/js/locales/amazeui.datetimepicker.zh-CN.js" charset="UTF-8"></script>
引入这两个感觉没有效果

**Comment by minwe** [comment]
**使用说明：**

1. 获取 Amaze UI Datetime Picker

  - [直接下载](https://github.com/amazeui/datetimepicker/archive/master.zip)

2. 引入 Datetime Picker 样式（`css` 目录下）以及 Amaze UI 样式：

  ```html
  <link rel="stylesheet" href="path/to/amazeui.min.css"/>
  <link rel="stylesheet" href="path/to/amazeui.datetimepicker.css"/>
  ```

3. 引入 jQuery 相关文件及 Datetime Picker JS 文件（下载包 `js` 目录下）：

  ```html
  <script src="path/to/jquery.min.js"></script>
  <script src="path/to/amazeui.datetimepicker.min.js"></script>
  ```

4. 初始化 Datetime Picker:

  ```html
  <input type="text" value="2015-02-15 21:05" id="datetimepicker" class="am-form-field">
  ```
  ```javascript
  $('#datetimepicker').datetimepicker({
    format: 'yyyy-mm-dd hh:ii'
  });
  ```
