### ISSUE TITLE
时间选择可以精确到秒吗

### ISSUE THREAD

**Issue by zhuCheer** [amazeui/datetimepicker#9]
如题，现在我只能设置精确到分

**Comment by minwe** [comment]
目前没有这个功能，精确到  0 秒还不够用？

**Comment by minwe** [comment]
http://eonasdan.github.io/bootstrap-datetimepicker/ 这个可以精确到秒

**Comment by minwe** [comment]
可以试用一下：
https://github.com/amazeui/datetimepicker-se
